variables:
  GIT_SSL_NO_VERIFY: 'true'
  ANSIBLE_CONFIG: ansible.cfg
  ANSIBLE_FORCE_COLOR: 'true'
  PY_COLORS: 1

.prepare_ssh_key: &prepare_ssh_key |
  mkdir -p ~/.ssh;echo "$DEMO_KEY" | tr -d '\r' > ~/.ssh/id_rsa;chmod 0600 ~/.ssh/id_rsa \
  && eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa

stages:
  - deploy_instances
  - deploy_common
  - deploy_docker
  - deploy_swarm
  - deploy_services

deploy_instances:
  image: harbor.carrion.ru/demo/ansible:latest
  stage: deploy_instances
  script:
    - ansible-playbook deploy.yml --tags deploy_instances
  tags:
    - demo
#  when: manual

common_tasks:
  image: harbor.carrion.ru/demo/ansible:latest
  stage: deploy_common
  before_script:
    - *prepare_ssh_key
  script:
    - ansible-playbook deploy.yml --tags deploy_common
  tags:
    - demo
  start_in: 5m
  when: delayed

deploy_docker:
  image: harbor.carrion.ru/demo/ansible:latest
  stage: deploy_docker
  before_script:
    - *prepare_ssh_key
  script:
    - ansible-playbook deploy.yml --tags deploy_docker
  tags:
    - demo
#  when: manual

deploy_swarm:
  image: harbor.carrion.ru/demo/ansible:latest
  stage: deploy_swarm
  before_script:
    - *prepare_ssh_key
  script:
    - ansible-playbook deploy.yml --tags deploy_swarm
  tags:
    - demo
#  when: manual

deploy_services:
  image: harbor.carrion.ru/demo/ansible:latest
  stage: deploy_services
  before_script:
    - *prepare_ssh_key
  script:
    - ansible-playbook deploy.yml --tags deploy_services
  tags:
    - demo
#  when: manual
