---
  - name: Init swarm
    docker_swarm:
      state: present
      advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    run_once: yes
    register: swarm_results
