---
  - name: Deploy demo app stack
    docker_stack:
      name: app
      resolve_image: never
      compose:
        - version: '3'
          services:
            demo:
              image: "{{ app_image }}"
              deploy:
                mode: replicated
                replicas: 3
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.demo.rule=Host(`{{ domain }}`)"
                  - "traefik.http.routers.demo.entrypoints=web"
                  - "traefik.http.services.demo.loadbalancer.server.port=80"
              networks:
                - traefik
          networks:
            traefik:
              external: true
                