---
  - name: Deploy front stack
    docker_stack:
      name: front
      resolve_image: never
      compose:
        - version: "3"
          services:
            traefik:
              image: "{{ traefik_image }}"
              command: 
                - "--api"
                - "--api.insecure=true"
                - "--api.dashboard=true"
                - "--api.debug=true"
                - "--providers.docker.endpoint=unix:///var/run/docker.sock"
                - "--providers.docker.swarmMode=true"
                - "--providers.docker.exposedbydefault=false"
                - "--providers.docker.network=traefik"
                - "--entrypoints.web.address=:80"
                - "--entrypoints.traefik.address=:81"
              deploy:
                mode: replicated
                replicas: 1
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
                  - "traefik.http.routers.dashboard.entrypoints=traefik"
                  - "traefik.http.routers.dashboard.service=api@internal"
                placement:
                  constraints:
                    - node.role == manager
              ports:
                - "80:80"
                - "81:81"
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock:ro
              networks:
                - traefik
          networks:
            traefik:
              external: true